# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rexample.proto\"\'\n\x03Pen\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x0c\n\x04\x61sdf\x18\x02 \x02(\t')
)




_PEN = _descriptor.Descriptor(
  name='Pen',
  full_name='Pen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='Pen.first_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asdf', full_name='Pen.asdf', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['Pen'] = _PEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pen = _reflection.GeneratedProtocolMessageType('Pen', (_message.Message,), dict(
  DESCRIPTOR = _PEN,
  __module__ = 'example_pb2'
  # @@protoc_insertion_point(class_scope:Pen)
  ))
_sym_db.RegisterMessage(Pen)


# @@protoc_insertion_point(module_scope)
